name: Build Qt Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential qtbase5-dev qtbase5-dev-tools qt5-qmake qttools5-dev-tools

    - name: Build Qt project and package
      run: |
        chmod +x build-package.sh
        ./build-package.sh

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: build/*.deb
