name: Build Qt Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt dependencies
      run: sudo apt-get update && sudo apt-get install -y qt5-default

    - name: Build Qt project and package
      run: |
        ./build-package.sh

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: build/*.deb
