name: Build Qt Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display directory contents for debugging
      run: ls -la .github/workflows/

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential qtbase5-dev qtbase5-dev-tools qt5-qmake qttools5-dev-tools freeglut3-dev

    - name: Make build-package.sh executable
      run: chmod +x .github/workflows/build-package.sh

    - name: Build Qt project and package
      run: .github/workflows/build-package.sh

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: teapot-qt-1.0.deb
