name: Package Debian Package
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
 
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
 
    - name: Build project
      run: rake build
 
    - name: Create deb package
      run: |
        fpm -s dir -t deb -a amd64 \
          -n your-package-name \
          -v $(cat VERSION) \
          --post-install ./postinst \
          --pre-remove ./prerm \
          -d 'ruby (>= 2.6.0)'` \
          -f \
          ./path/to/your/project/bin=/usr/bin/your-executable \
          ./path/to/your/project/config=/etc/your-config
      env:
        VERSION: 1.0.0
